# Generated by Django 4.2.11 on 2024-04-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_goal_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
