# Generated by Django 4.2.11 on 2024-04-21 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created_on']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
    ]
