# Generated by Django 4.2.11 on 2024-05-02 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_delete_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='content',
            new_name='body',
        ),
    ]
