# Generated by Django 4.2.11 on 2024-05-04 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_rename_content_goal_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='slug',
        ),
    ]
