# Generated by Django 4.2.11 on 2024-04-26 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_delete_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0002_remove_task_content_remove_task_title_task_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todo.goal'),
        ),
    ]
